from __future__ import annotations

import os
import stat
import tempfile
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Awaitable, Callable, Protocol

from app.config import settings
from app.schemas.applications import ApplicationManifest, ProcessRuntime, validate_manifest_paths


MAX_UNIT_BYTES = 64 * 1024


class UnitError(RuntimeError):
    pass


class CommandOutcome(Protocol):
    succeeded: bool
    message: str


CommandRunner = Callable[[list[str], Path | None, int], Awaitable[CommandOutcome]]


class UnitConsistency(str, Enum):
    MATCH = "MATCH"
    MISSING = "MISSING"
    MISMATCH = "MISMATCH"
    UNSAFE = "UNSAFE"
    NOT_PROCESS = "NOT_PROCESS"


@dataclass(frozen=True)
class UnitConsistencyResult:
    application_id: str
    unit_name: str | None
    status: UnitConsistency
    message: str = ""


def unit_name_for(application_id: str) -> str:
    # The manifest schema has already constrained IDs; keep this defense local too.
    if not application_id or any(
        char not in "abcdefghijklmnopqrstuvwxyz0123456789-" for char in application_id
    ):
        raise UnitError("Application id cannot be converted to a safe unit name")
    if application_id.startswith("-") or application_id.endswith("-"):
        raise UnitError("Application id cannot be converted to a safe unit name")
    return f"machinedeck-{application_id}.service"


def _reject_control_characters(value: str, field: str) -> None:
    if any(character in value for character in ("\n", "\r", "\x00")):
        raise UnitError(f"{field} cannot contain newlines or null bytes")


def _quote(value: str, *, escape_dollar: bool = False) -> str:
    _reject_control_characters(value, "systemd value")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    if escape_dollar:
        escaped = escaped.replace("$", "$$")
    return f'"{escaped}"'


def _escape_path(value: str) -> str:
    """Escape a path as an unquoted systemd setting value."""
    _reject_control_characters(value, "systemd path")
    output = []
    safe = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/._-"
    for byte in value.encode("utf-8"):
        if byte in safe:
            output.append(chr(byte))
        elif byte == ord("%"):
            output.append("%%")
        else:
            output.append(f"\\x{byte:02x}")
    return "".join(output)


def render_user_unit(manifest: ApplicationManifest) -> str:
    """Render a complete unit without interpreting manifest data as directives or shell."""
    if not isinstance(manifest.runtime, ProcessRuntime):
        raise UnitError("Only process manifests can render a systemd user unit")
    validation = validate_manifest_paths(manifest)
    if not validation.valid:
        raise UnitError("; ".join(issue.message for issue in validation.errors))
    unit_name = unit_name_for(manifest.id)
    command = " ".join(_quote(argument, escape_dollar=True) for argument in manifest.runtime.command)
    lines = [
        "# Generated by MachineDeck. Manual changes will be detected and replaced.",
        "[Unit]",
        f"Description=MachineDeck managed application {unit_name}",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=simple",
        f"WorkingDirectory={_escape_path(str(manifest.runtime.working_dir))}",
        f"ExecStart={command}",
    ]
    for name, value in sorted(manifest.environment.items()):
        _reject_control_characters(value, f"environment variable {name}")
        lines.append(f"Environment={_quote(f'{name}={value}')}")
    lines.extend(
        [
            "KillMode=control-group",
            "TimeoutStartSec=120",
            "TimeoutStopSec=30",
            "Restart=no",
            "NoNewPrivileges=true",
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )
    rendered = "\n".join(lines)
    validate_rendered_unit(rendered)
    return rendered


def validate_rendered_unit(content: str) -> None:
    encoded = content.encode("utf-8")
    if len(encoded) > MAX_UNIT_BYTES:
        raise UnitError("Rendered unit exceeds the maximum size")
    if not content.endswith("\n") or "\r" in content or "\x00" in content:
        raise UnitError("Rendered unit contains invalid control characters")
    sections: list[str] = []
    directives: dict[str, int] = {}
    allowed = {
        "Description",
        "After",
        "Wants",
        "Type",
        "WorkingDirectory",
        "ExecStart",
        "Environment",
        "KillMode",
        "TimeoutStartSec",
        "TimeoutStopSec",
        "Restart",
        "NoNewPrivileges",
        "WantedBy",
    }
    for line in content.splitlines():
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            sections.append(line)
            continue
        key, separator, _ = line.partition("=")
        if not separator or key not in allowed:
            raise UnitError(f"Rendered unit contains an unsupported directive: {key or line}")
        directives[key] = directives.get(key, 0) + 1
    if sections != ["[Unit]", "[Service]", "[Install]"]:
        raise UnitError("Rendered unit has unexpected or out-of-order sections")
    for required in ("WorkingDirectory", "ExecStart", "KillMode"):
        if directives.get(required) != 1:
            raise UnitError(f"Rendered unit must contain exactly one {required} directive")


class UserUnitManager:
    def __init__(self, unit_dir: Path = settings.user_unit_dir) -> None:
        self.unit_dir = unit_dir.expanduser()

    def _trusted_directory(self, *, create: bool) -> Path:
        if create:
            self.unit_dir.mkdir(mode=0o755, parents=True, exist_ok=True)
        try:
            metadata = self.unit_dir.lstat()
        except FileNotFoundError as exc:
            raise UnitError(f"User unit directory does not exist: {self.unit_dir}") from exc
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
            raise UnitError("User unit directory must be a real directory, not a symlink")
        if metadata.st_uid != os.geteuid():
            raise UnitError("User unit directory must be owned by the MachineDeck user")
        if metadata.st_mode & 0o022:
            raise UnitError("User unit directory cannot be group- or world-writable")
        return self.unit_dir.resolve(strict=True)

    def target_path(self, application_id: str, *, create_directory: bool = False) -> Path:
        directory = self._trusted_directory(create=create_directory)
        target = directory / unit_name_for(application_id)
        try:
            metadata = target.lstat()
        except FileNotFoundError:
            return target
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise UnitError("Managed unit target must be a regular file, not a symlink")
        if metadata.st_uid != os.geteuid() or metadata.st_mode & 0o022:
            raise UnitError("Managed unit target has unsafe ownership or write permissions")
        return target

    @staticmethod
    def _read_regular(target: Path) -> bytes:
        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        try:
            descriptor = os.open(target, flags)
        except FileNotFoundError:
            raise
        except OSError as exc:
            raise UnitError(f"Cannot safely read managed unit: {exc}") from exc
        try:
            metadata = os.fstat(descriptor)
            if not stat.S_ISREG(metadata.st_mode):
                raise UnitError("Managed unit target must remain a regular file")
            chunks = []
            total = 0
            while True:
                chunk = os.read(descriptor, 8192)
                if not chunk:
                    break
                total += len(chunk)
                if total > MAX_UNIT_BYTES:
                    raise UnitError("Existing managed unit exceeds the maximum size")
                chunks.append(chunk)
            return b"".join(chunks)
        finally:
            os.close(descriptor)

    @staticmethod
    def _atomic_replace(target: Path, content: bytes) -> None:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
        )
        temporary = Path(temporary_name)
        try:
            os.fchmod(descriptor, 0o644)
            with os.fdopen(descriptor, "wb") as stream:
                descriptor = -1
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, target)
            directory_descriptor = os.open(target.parent, os.O_RDONLY)
            try:
                os.fsync(directory_descriptor)
            finally:
                os.close(directory_descriptor)
        finally:
            if descriptor >= 0:
                os.close(descriptor)
            temporary.unlink(missing_ok=True)

    async def install(
        self, manifest: ApplicationManifest, runner: CommandRunner
    ) -> "UnitInstallReceipt":
        rendered = render_user_unit(manifest)
        target = self.target_path(manifest.id, create_directory=True)
        new_content = rendered.encode("utf-8")
        try:
            previous = self._read_regular(target)
        except FileNotFoundError:
            previous = None
        if previous == new_content:
            return UnitInstallReceipt(self, target, previous, changed=False)

        # Validate the exact staged bytes before they replace the active definition.
        descriptor, staged_name = tempfile.mkstemp(
            prefix=f".{target.stem}.", suffix=".service", dir=target.parent
        )
        staged = Path(staged_name)
        try:
            os.fchmod(descriptor, 0o644)
            with os.fdopen(descriptor, "wb") as stream:
                descriptor = -1
                stream.write(new_content)
                stream.flush()
                os.fsync(stream.fileno())
            verified = await runner(["systemd-analyze", "--user", "verify", str(staged)], None, 30)
            if not verified.succeeded:
                raise UnitError(verified.message or "systemd-analyze rejected the rendered unit")
        finally:
            if descriptor >= 0:
                os.close(descriptor)
            staged.unlink(missing_ok=True)

        self._atomic_replace(target, new_content)
        receipt = UnitInstallReceipt(self, target, previous, changed=True)
        reloaded = await runner(["systemctl", "--user", "daemon-reload"], None, 30)
        if not reloaded.succeeded:
            await receipt.rollback(runner)
            raise UnitError(reloaded.message or "systemd user daemon-reload failed")
        return receipt

    def consistency(self, manifest: ApplicationManifest) -> UnitConsistencyResult:
        if not isinstance(manifest.runtime, ProcessRuntime):
            return UnitConsistencyResult(manifest.id, None, UnitConsistency.NOT_PROCESS)
        unit_name = unit_name_for(manifest.id)
        try:
            expected = render_user_unit(manifest).encode("utf-8")
            if not self.unit_dir.exists():
                return UnitConsistencyResult(manifest.id, unit_name, UnitConsistency.MISSING)
            target = self.target_path(manifest.id)
            if not target.exists():
                return UnitConsistencyResult(manifest.id, unit_name, UnitConsistency.MISSING)
            if self._read_regular(target) == expected:
                return UnitConsistencyResult(manifest.id, unit_name, UnitConsistency.MATCH)
            return UnitConsistencyResult(
                manifest.id, unit_name, UnitConsistency.MISMATCH, "Unit content differs from the database manifest"
            )
        except UnitError as exc:
            return UnitConsistencyResult(manifest.id, unit_name, UnitConsistency.UNSAFE, str(exc))


@dataclass
class UnitInstallReceipt:
    manager: UserUnitManager
    target: Path
    previous_content: bytes | None
    changed: bool
    rolled_back: bool = False

    async def rollback(self, runner: CommandRunner) -> None:
        if not self.changed or self.rolled_back:
            return
        if self.previous_content is None:
            self.target.unlink(missing_ok=True)
        else:
            self.manager._atomic_replace(self.target, self.previous_content)
        self.rolled_back = True
        await runner(["systemctl", "--user", "daemon-reload"], None, 30)
